url: https://hbtumun17.netlify.com
baseurl: /

# Site settings
title: HBTU MUN
email: rohit.goswami@aol.com
description: "Details for the HBTU MUN 2017, held at HBTU during Odyssey 2017"


# EB names, titles and social links
people:
- name: Amit Batra
  pic: 1
  position: Secretary General
  social:
#    - title: twitter
#      url: #
    - title: facebook
      url: https://www.facebook.com/amit.batra.5
#    - title: stack-overflow
#      url: #

- name: Rohit Goswami
  pic: 2
  position: Chairperson
  social:
    - title: github
      url: https://www.github.com/HaoZeke
    - title: facebook
      url: https://www.facebook.com/HaoZeke
    - title: linkedin
      url: https://www.linkedin.com/in/rohit-goswami-513835a9

- name: Sakshi Srivastava
  pic: 3
  position: Vice Chairperson
  social:
#    - title: twitter
#      url: #
    - title: facebook
      url: 
#    - title: google-plus
#      url: #

- name: Shaivya Anand
  pic: 4
  position: Vice Chairperson
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/shaivya-anand-a60493104
    - title: facebook
      url: https://www.facebook.com/shaivya.anand
#    - title: google-plus
#      url: #

- name: Pranjal Srivastava
  pic: 5
  position: Special Rapporteur
  social:
#    - title: twitter
#      url: #
    - title: facebook
      url: https://www.facebook.com/pranjal1705
#    - title: google-plus
#      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: twitter
#    url: http://twitter.com/jekyllrb
  - title: facebook
    url: #
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket 
#    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/HaoZeke/HBTU_MUN

# Postal address (add as many lines as necessary)
address:
  - line: Harcourt Butler Technical University, Nawabganj
  - line: Kanpur (U.P.) – 208 002

# Build settings
markdown: kramdown
permalink: pretty

# Plugins
plugins:
  - jekyll-sitemap